/*
 * Slave_Commands.h
 *
 * Created: 13/01/2025 17:27:57
 *  Author: pc
 */ 


#ifndef SLAVE_COMMANDS_H_
#define SLAVE_COMMANDS_H_
#define ROOM_ONE_LIGHT_TURN_ON 0X01
#define ROOM_ONE_LIGHT_TURN_OFF 0X02
#define ROOM_ONE_STATUS 0X03
#define ROOM_TWO_LIGHT_TURN_ON 0X04
#define ROOM_TWO_LIGHT_TURN_OFF 0X05
#define ROOM_TWO_STATUS 0X06
#define ROOM_THREE_LIGHT_TURN_ON 0X07
#define ROOM_THREE_LIGHT_TURN_OFF 0X08
#define ROOM_THREE_STATUS 0X09
#define ROOM_FOUR_LIGHT_TURN_ON 0X0A
#define ROOM_FOUR_LIGHT_TURN_OFF 0X0B
#define ROOM_FOUR_STATUS 0X0C
#define TV_TURN_ON 0X0D
#define TV_TURN_OFF 0X0F
#define TV_STATUS 0X10
#define AC_TURN_ON 0X11
#define AC_TURN_OFF 0X12
#define AC_STATUS 0X13
#define AC_TEMP_CONTROL 0X14
#define DUMMY 0XFF
#define ADDRESS_DESIRED_TEMP 0X20
#define ADDRESS_TURN_ON_AC_LAST 0X21
#define ADDRESS_ROOMS 0X22
#define ADDRESS_TV_TURN_ON_LAST 0X26
#endif /* SLAVE_COMMANDS_H_ */